plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '9.0.0'
}

application {
    mainClass = 'Main'
}

group = 'IDONTKNOW'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

project.ext.lwjglVersion = "3.4.1"
project.ext.jomlVersion = "1.10.8"
project.ext.lwjglNatives = "natives-windows"

repositories {
    mavenCentral()
}

dependencies {
    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-assimp"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation "org.lwjgl:lwjgl-nfd"
    implementation "org.lwjgl:lwjgl-openal"
    implementation "org.lwjgl:lwjgl-opengl"
    implementation "org.lwjgl:lwjgl-stb"
    implementation "org.lwjgl:lwjgl::$lwjglNatives"
    implementation "org.lwjgl:lwjgl-assimp::$lwjglNatives"
    implementation "org.lwjgl:lwjgl-glfw::$lwjglNatives"
    implementation "org.lwjgl:lwjgl-nfd::$lwjglNatives"
    implementation "org.lwjgl:lwjgl-openal::$lwjglNatives"
    implementation "org.lwjgl:lwjgl-opengl::$lwjglNatives"
    implementation "org.lwjgl:lwjgl-stb::$lwjglNatives"
    implementation "org.joml:joml:${jomlVersion}"
}

//     .\gradlew packageWindows
//     .\gradlew clean packageWindows
tasks.register('packageWindows', Exec) {
    dependsOn tasks.shadowJar

    def outputDir = layout.buildDirectory.dir('jpackage').get().asFile
    def appDir = new File(outputDir, 'RayMarchBlackHole')
    def jarFile = tasks.shadowJar.archiveFile.get().asFile

    doFirst {
        delete outputDir
        outputDir.mkdirs()

        commandLine(
                'jpackage',
                '--input', jarFile.parent,
                '--main-jar', jarFile.name,
                '--main-class', application.mainClass.get(),
                '--name', 'RayMarchBlackHole',
                '--type', 'app-image',
                '--dest', outputDir.absolutePath
        )
    }

    doLast {
        copy {
            from 'assets'
            into new File(appDir, 'assets')
        }
    }
}